services:
  app:
    build: .
    command: sh -c "npm install && npm run dev"
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - node_modules:/app/node_modules

volumes:
  node_modules:
